baseURL = 'https://emilyport.com/'
languageCode = 'en-us'
title = 'About Me'
sectionPagesMenu = 'main'
pluralizeListTitles = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
